# Generated by Django 2.1.7 on 2019-03-06 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wonderapp', '0003_auto_20190306_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text=' UUID to be the primary key', primary_key=True, serialize=False),
        ),
    ]
