# Generated by Django 2.1.7 on 2019-03-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderapp', '0006_auto_20190306_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
